import Breadcrumb from "../../../../components/Breadcrumb";
import BannerSection from "../../../../components/BannerSection";
import styles from "./RegionalTourGuides.module.css";
import { faHome } from "@fortawesome/free-solid-svg-icons";

const tourGuides = [
  {
    no: "1",
    name: "Daw Htay Htay Tin",
    licenseNo: "G(YGN)-0001",
    licenseDate: "",
    language: "English/French",
    address: "No-8/ka, Kaymarthi St, Michaungkan Region(3), Thingangyun Tsp, Ygn.",
    phone: "",
  },
  {
    no: "2",
    name: "U Kyaw Win Mg",
    licenseNo: "G(YGN)-0002",
    licenseDate: "",
    language: "English/French",
    address: "No-18, Manahaye St, Mahlawgone Qr, Tamwe Tsp, Ygn.",
    phone: "",
  },
  {
    no: "3",
    name: "Daw Rose Marthar",
    licenseNo: "G(YGN)-0003",
    licenseDate: "",
    language: "English/Japanese",
    address: "No-69/5, Sanchaung St, N/Sanchaung Qr, Sanchaung Tsp, Ygn.",
    phone: "",
  },
  {
    no: "4",
    name: "U Aung Kyaw Lin",
    licenseNo: "G(YGN)-0004",
    licenseDate: "",
    language: "English/Japanese",
    address: "No-65, Ayeyarwaddy St, Ahlone Tsp, Ygn.",
    phone: "",
  },
  {
    no: "5",
    name: "U Win Kyawe",
    licenseNo: "G(YGN)-0005",
    licenseDate: "",
    language: "English/French",
    address: "No-96, Five Flr, Shan St, Sanchaung Tsp, Ygn.",
    phone: "",
  },
  {
    no: "6",
    name: "Daw Myint Myint Maw",
    licenseNo: "G(YGN)-0006",
    licenseDate: "",
    language: "Chinese/French",
    address: "No-396, Lower Pazuntaung St, Pazuntaung Tsp, Ygn.",
    phone: "",
  },
  {
    no: "7",
    name: "Daw Toe Khin Khin",
    licenseNo: "G(YGN)-0007",
    licenseDate: "",
    language: "English/Japanese",
    address: "No-203/23, East Yankin Tsp, Ygn.",
    phone: "",
  },
  {
    no: "8",
    name: "U Myat Wanna",
    licenseNo: "G(YGN)-0008",
    licenseDate: "",
    language: "English",
    address: "Bldg-204, Rm.18, East Yankin Tsp, Ygn.",
    phone: "",
  },
  {
    no: "9",
    name: "Daw Tan Pate Lyan",
    licenseNo: "G(YGN)-0009",
    licenseDate: "",
    language: "English/Japanese",
    address: "No.30, Lanmadaw Rd, Latha Tsp, Ygn.",
    phone: "",
  },
  {
    no: "10",
    name: "Daw Khin Khin Swe",
    licenseNo: "G(YGN)-0010",
    licenseDate: "",
    language: "English/Japanese",
    address: "No.(30), 3-Flr, New Yaetarshae St, Bahan Tsp, Ygn.",
    phone: "95133146",
  },
  {
    no: "11",
    name: "U Thin New",
    licenseNo: "G(YGN)-0011",
    licenseDate: "",
    language: "English/Japanese",
    address: "No.(554/c), Nant Tharkone Qtr, Insein Tsp., Ygn.",
    phone: "9430959731",
  },
  {
    no: "12",
    name: "Daw Mar Lar Lwin",
    licenseNo: "G(YGN)-0012",
    licenseDate: "",
    language: "Japanese",
    address: "No.(277), Damayone Rd., (13)Qtr, Yankin Tsp, Ygn.",
    phone: "642136",
  },
  {
    no: "13",
    name: "U Htin Aung Kyi",
    licenseNo: "G(YGN)-0013",
    licenseDate: "",
    language: "English/Italian",
    address: "No.19, Aung Thiri (4) St, 28-Qr, N/Dagon Tsp, Ygn.",
    phone: "578189",
  },
  {
    no: "14",
    name: "U Tin Khine",
    licenseNo: "G(YGN)-0014",
    licenseDate: "",
    language: "Chinese/Japanese",
    address: "No.(641)1Fl. 21 St.Latha Tsp, Ygn.",
    phone: "95102801",
  },
  {
    no: "15",
    name: "Daw Khin Myat Thu",
    licenseNo: "G(YGN)-0015",
    licenseDate: "",
    language: "English",
    address: "No.(55/4), Boyarnyunt St. Dagon Tsp, Ygn.",
    phone: "95102801",
  },
  {
    no: "16",
    name: "U Soe Myint",
    licenseNo: "G(YGN)-0016",
    licenseDate: "",
    language: "English/French",
    address: "Bldg.(9) 4 Flr®, Danatheikdi St , (2)Qr. Mayangone Tsp. Ygn.",
    phone: "95117786",
  },
  {
    no: "17",
    name: "Daw Soe Nyunt Kyine",
    licenseNo: "G(YGN)-0017",
    licenseDate: "",
    language: "English",
    address: "No.(118)Kyun Shwemyaing Lane (2), Thingangyun Tsp. Ygn.",
    phone: "95155062",
  },
  {
    no: "18",
    name: "Daw Yi Yi Han",
    licenseNo: "G(YGN)-0018",
    licenseDate: "",
    language: "English",
    address: "No.(55/2)(A) (14)St. Lanmadaw Tsp.Ygn.",
    phone: "1210828",
  },
  {
    no: "19",
    name: "U Kyaw Soe Myint",
    licenseNo: "G(YGN)-0019",
    licenseDate: "",
    language: "English/French",
    address: "No(8/c) Maykha St. Mayangone Tsp. Ygn.",
    phone: "",
  },
  {
    no: "20",
    name: "Daw Kyi Kyi Aye",
    licenseNo: "G(YGN)-0020",
    licenseDate: "",
    language: "English",
    address: "No.(43) Myintmo St. Sanchaung Tsp.Ygn.",
    phone: "95144006",
  },
  {
    no: "21",
    name: "Daw Khin Thein Win",
    licenseNo: "G(YGN)-0021",
    licenseDate: "",
    language: "English/French",
    address: "Bldg.(L/406) No.47, Baho St. Manaw Hayi Yeikthar . Ahlone Tsp. Ygn.",
    phone: "95155859",
  },
  {
    no: "22",
    name: "U Win Myint Saw Maine",
    licenseNo: "G(YGN)-0022",
    licenseDate: "",
    language: "English",
    address: "No(64). Rm F/2. Ahwaiyar Housing , Myintar Nyunt Qr, Tamwe Tsp.Ygn.",
    phone: "95115625",
  },
  {
    no: "23",
    name: "Daw San San Tun",
    licenseNo: "G(YGN)-0023",
    licenseDate: "",
    language: "English/Italian",
    address: "Bldg.(4)Rm 11. Link St. , Shwegondine , Bahan Tsp. Ygn.",
    phone: "",
  },
  {
    no: "24",
    name: "U Mg Mg Than",
    licenseNo: "G(YGN)-0024",
    licenseDate: "",
    language: "English",
    address: "No(19/B) Nawaday St., Yawmimgyi Qr, Dagon Tsp, Ygn.",
    phone: "9420020020",
  },
  {
    no: "25",
    name: "U Nyi Nyi Chit Hla",
    licenseNo: "G(YGN)-0025",
    licenseDate: "",
    language: "English/Japanese",
    address: "No.(53) Yaekyaw St. Puzundaung Tsp. Ygn.",
    phone: "389045",
  },
  {
    no: "26",
    name: "U Kyaw Oo",
    licenseNo: "G(YGN)-0026",
    licenseDate: "",
    language: "English/French",
    address: "No(36/556) Peral St. N/Dagon Myothit Tsp. Ygn.",
    phone: "",
  },
  {
    no: "27",
    name: "U Aung Zaw Myint",
    licenseNo: "G(YGN)-0027",
    licenseDate: "",
    language: "English/Spanish",
    address: "No(83)Myawutyee St. (29)Qr. Thuwunna , Thingangyun Tsp. Ygn.",
    phone: "580076",
  },
  {
    no: "28",
    name: "U Myat Tun",
    licenseNo: "G(YGN)-0028",
    licenseDate: "",
    language: "English",
    address: "No(141/2) Meedone St. Thingangyun Tsp. Ygn.",
    phone: "92047902",
  },
    {
    no: "29",
    name: "U Phone Mg",
    licenseNo: "G(YGN)-0029",
    language: "English/French",
    address: "Bldg (30) Rm. (15) Thunandar St. (10)Qr. Hlaing Tsp. Ygn.",
    phone: "95132748",
  },
  {
    no: "30",
    name: "U Myo Nyunt",
    licenseNo: "G(YGN)-0030",
    language: "English",
    address: "No(325) Naykyar St. (45)Qr. N/Dagon Tsp. Ygn.",
    phone: "95132748",
  },
  {
    no: "31",
    name: "Daw Cho Cho Myint",
    licenseNo: "G(YGN)-0031",
    language: "English",
    address: "No(141/2)MeedonSt.Thingangyun Tsp.Ygn.",
    phone: "95401160",
  },
  {
    no: "32",
    name: "U Tin Naing (&) Khin Kyaw",
    licenseNo: "G(YGN)-0032",
    language: "French",
    address: "No(134)(42)St. (8)Qr.Botathaung Tsp. Ygn.",
    phone: "95163559",
  },
  {
    no: "33",
    name: "U Mya Win Mg",
    licenseNo: "G(YGN)-0033",
    language: "English/German",
    address: "No.(5a/557)Maydarwi Rd. (Salein)Qr. N/Okkalapa Tsp. Ygn.",
    phone: "95088768",
  },
  {
    no: "34",
    name: "U Cho Win",
    licenseNo: "G(YGN)-0034",
    language: "Japanese",
    address: "No.(57)(41)St, Botathaung Tsp. Ygn.",
    phone: "01382795/95152460",
  },
  {
    no: "35",
    name: "Daw Kyi Kyi Sein",
    licenseNo: "G(YGN)-0035",
    language: "French",
    address: "No(19/D)Chit Yeikmon St.Ygn-Insein Rd. Mayangone Tsp. Ygn.",
    phone: "",
  },
  {
    no: "36",
    name: "U Hla Myint",
    licenseNo: "G(YGN)-0036",
    language: "English",
    address: "No(18/kha)Hledan(7)St. (3)Qr. Kamayut Tsp. Ygn.",
    phone: "95167988",
  },
  {
    no: "37",
    name: "Daw Khin Thida Aye",
    licenseNo: "G(YGN)-0037",
    language: "English/Spanish",
    address: "No(704/B)Peral Condo, Kabaraye Pagoda Rd. Bahan Tsp. Ygn.",
    phone: "",
  },
  {
    no: "38",
    name: "Daw Yin Yin Sein",
    licenseNo: "G(YGN)-0038",
    language: "German",
    address: "No.(12) Zizawar St. Ngwe Kyaryan Yeikthar , S/Okkalpa Tsp. Ygn.",
    phone: "9421755320",
  },
  {
    no: "39",
    name: "U Soe Win",
    licenseNo: "G(YGN)-0039",
    language: "English/Chinese",
    address: "No(405/a) Myintzu St. (5)Qr. E / Dagon Tsp. Ygn.",
    phone: "933154960",
  },
  {
    no: "40",
    name: "U Than Tun Aung (&) Ba Nyein",
    licenseNo: "G(YGN)-0040",
    language: "English/Italian",
    address: "No(5/74)Aung Tayza St. Manyangon Tsp. Ygn.",
    phone: "",
  },
  {
    no: "41",
    name: "Daw PS Kalar Ni Khine",
    licenseNo: "G(YGN)-0041",
    language: "German",
    address: "No-25 ,Shwe Hnini Si Lane(3), 5-Qr , Mayangone Tsp. Ygn.",
    phone: "",
  },
  {
    no: "42",
    name: "U Saw Hla Chit",
    licenseNo: "G(YGN)-0042",
    language: "Japanese",
    address: "No(908). (1)St. E/Gyoegone Insein Tsp. Ygn.",
    phone: "95177628",
  },
  {
    no: "43",
    name: "U Myo Win",
    licenseNo: "G(YGN)-0043",
    language: "English",
    address: "N0-18/5/B ,Maharzaya St ,Yae Kyaw, Pazuntaung Tsp ,Ygn.",
    phone: "1294977",
  },
  {
    no: "44",
    name: "U Zaw Myint",
    licenseNo: "G(YGN)-0044",
    language: "English",
    address: "No(28/A/3)Kokkine Swimming Pool St, Bahan Tsp, Ygn.",
    phone: "",
  },
  {
    no: "45",
    name: "Daw Tin Pyone Khin",
    licenseNo: "G(YGN)-0045",
    language: "English",
    address: "No.(A/302)Peral Center , Bahan Tsp. Ygn.",
    phone: "",
  },
  {
    no: "46",
    name: "U Moe Aung Lwin",
    licenseNo: "G(YGN)-0046",
    language: "English",
    address: "Bldg-5 Rm.2/ka. Thiri St. Sanchaung Tsp. Ygn.",
    phone: "973234841",
  },
  {
    no: "47",
    name: "Daw Nu Nu Yin",
    licenseNo: "G(YGN)-0047",
    language: "English",
    address: "No-25 Shwe Hninsi(3)St. 5-Qr. Mayangone Tsp. Ygn.",
    phone: "",
  },
  {
    no: "48",
    name: "Daw Thet Thet Naing",
    licenseNo: "G(YGN)-0048",
    language: "English/French",
    address: "No-8. Thuzitar St. Thingangyun Tsp. Ygn.",
    phone: "95175646",
  },
  {
    no: "49",
    name: "Daw May May Thet",
    licenseNo: "G(YGN)-0049",
    language: "English/French",
    address: "Bldg-6 Rm.(4)Than Thumar St. S/Okkalapa Tsp. Ygn.",
    phone: "",
  },
  {
    no: "50",
    name: "Daw Kye Kye Mar",
    licenseNo: "G(YGN)-0050",
    language: "English",
    address: "No.12/kha, U Waisara Housing , Dagon Tsp, Ygn.",
    phone: "",
  },
  {
    no: "51",
    name: "U Ye Lwin",
    licenseNo: "G(YGN)-0051",
    language: "Chinese",
    address: "No(173/ka)Myaung Gyi St, Yaekyaw, Puzuntaung Tsp. Ygn.",
    phone: "01296275/0973057919",
  },
  {
    no: "52",
    name: "Daw Nan Loung Khan",
    licenseNo: "G(YGN)-0052",
    language: "German",
    address: "Bldg(22)Rm.(22) Hlaing Tsp, Ygn.",
    phone: "95149371",
  },
  {
    no: "53",
    name: "U Han Htet Aung",
    licenseNo: "G(YGN)-0053",
    language: "English",
    address: "No(16)F-Shwe Bo St/Tamwe Tsp, Ygn.",
    phone: "",
  },
  {
    no: "54",
    name: "U Thant Zaw Nyien",
    licenseNo: "G(YGN)-0054",
    language: "English",
    address: "No.(27)Yandana Mon(3)St. 5-Qr. Hlaing Tsp. Ygn.",
    phone: "",
  },
  {
    no: "55",
    name: "Daw Khin May Phyu",
    licenseNo: "G(YGN)-0055",
    language: "Japanese",
    address: "No(3/B)Near Sin Min Market. Ahlone Tsp, Ygn.",
    phone: "",
  },
  {
    no: "56",
    name: "U Mg Mg",
    licenseNo: "G(YGN)-0056",
    language: "English/Japanese",
    address: "Bldg(c) No(54)Bonyar Nyunt St. Dagon Tsp. Ygn.",
    phone: "",
  },
  {
    no: "57",
    name: "U Sein Win",
    licenseNo: "G(YGN)-0057",
    language: "English/French",
    address: "No-304/D/1, Bahan Tsp, Ygn.",
    phone: "",
  },
  {
    no: "58",
    name: "Daw Khin Than Nwe",
    licenseNo: "G(YGN)-0058",
    language: "Japanese",
    address: "No(27/B-3)Pathein St. Sangaung Tsp. Ygn.",
    phone: "95183114",
  },
  {
    no: "59",
    name: "U Win Myint",
    licenseNo: "G(YGN)-0059",
    language: "English/French",
    address: "No.(10)Khaymarthi St. Thingangyun Tsp.Ygn.",
    phone: "09926253 629139",
  },
  {
    no: "60",
    name: "U Myint Oo",
    licenseNo: "G(YGN)-0060",
    language: "English/Thai",
    address: "Bldg-2. Rm.205. Asamyut Tsp. Ygn.",
    phone: "570611",
  },
  {
    no: "61",
    name: "U Saw Chit Oo",
    licenseNo: "G(YGN)-0061",
    language: "English",
    address: "No.52, Sadan St. Ahlone Tsp. Ygn.",
    phone: "",
  },
  {
    no: "62",
    name: "U Hla Myint",
    licenseNo: "G(YGN)-0062",
    language: "German",
    address: "No-47, 3 Fl, Kyaukmyuang, Tamwe Tsp. Ygn.",
    phone: "",
  },
  {
    no: "63",
    name: "U Tan D Soe",
    licenseNo: "G(YGN)-0063",
    language: "English/Japanese",
    address: "No.31/28, Aungmingalar St, Phawkan Qr. Insein Tsp. Ygn.",
    phone: "",
  },
  {
    no: "64",
    name: "U Bin Sin Soe Myint",
    licenseNo: "G(YGN)-0064",
    language: "English",
    address: "No.5, Masoeyein kyaung St, 9-mile, Mayangone Tsp. Ygn.",
    phone: "646067",
  },
  {
    no: "65",
    name: "Daw Zaka War Soe",
    licenseNo: "G(YGN)-0065",
    language: "English/Thai",
    address: "Bldg.2, Rm.205- Aungmyay Tharsi Housing, Kamayut Tsp. Ygn.",
    phone: "",
  },
  {
    no: "66",
    name: "U Tin Aung Moe",
    licenseNo: "G(YGN)-0066",
    language: "English",
    address: "No.29, Sanchaung St. Sanchaung Tsp, Ygn.",
    phone: "",
  },
  {
    no: "67",
    name: "Daw Maw Maw Aung",
    licenseNo: "G(YGN)-0067",
    language: "English",
    address: "No.(F/120), Khayae St, Bagan, Mdy.",
    phone: "",
  },
  {
    no: "68",
    name: "U Win Tin",
    licenseNo: "G(YGN)-0068",
    language: "Japanese",
    address: "No54/A, 94 St. Mingalar Taung Nyunt Tsp, Ygn.",
    phone: "",
  },
  {
    no: "69",
    name: "U Hla Win",
    licenseNo: "G(YGN)-0069",
    language: "English/Chinese",
    address: "No.20, Upper FL, 24 St, Lathar Tsp, Ygn.",
    phone: "95116459",
  },
  {
    no: "70",
    name: "U Aung Kyaw",
    licenseNo: "G(YGN)-0070",
    language: "Japanese",
    address: "No(3/164)Kangaw St. Waibargi Myothit, N/Okkalapla Tsp. Ygn.",
    phone: "",
  },
  {
    no: "71",
    name: "U Aung Aung Kyaw",
    licenseNo: "G(YGN)-0071",
    language: "English",
    address: "No-2/B/840 , Muditar Condo-2 ,16-Qr ,Insein Tsp, Ygn.",
    phone: "",
  },
  {
    no: "72",
    name: "UHla Mg",
    licenseNo: "G(YGN)-0072",
    language: "English",
    address: "No(8) Upper Puzundaung St. Mingalar Taungnyut Tsp, Ygn.",
    phone: "",
  },
  {
    no: "73",
    name: "U Tin Moe",
    licenseNo: "G(YGN)-0073",
    language: "English",
    address: "No(81)32 St, Ground Fl,Pabedan Tsp, Ygn.",
    phone: "",
  },
  {
    no: "74",
    name: "U Mya Lwin",
    licenseNo: "G(YGN)-0074",
    language: "Japanese",
    address: "No.37, Thantadar St, Sanchaung Tsp, Ygn.",
    phone: "",
  },
  {
    no: "75",
    name: "Daw Moe Moe Thein",
    licenseNo: "G(YGN)-0075",
    language: "English",
    address: "No.E/4,Shwe Yinmar St,Kamaryut Tsp,Ygn.",
    phone: "",
  },
  {
    no: "76",
    name: "Daw Yi Yi Thein",
    licenseNo: "G(YGN)-0076",
    language: "English",
    address: "No.206/26, E/Yankin, Yankin Tsp, Ygn.",
    phone: "",
  },
  {
    no: "77",
    name: "U Tin Mg Hlaing",
    licenseNo: "G(YGN)-0077",
    language: "English/Japanese",
    address: "Bldg 10, Rm.11, Shwe Onphin Housing, 5 Qr, W/Yankin Tsp, Ygn.",
    phone: "95162001",
  },
  {
    no: "78",
    name: "Daw Khin Nwe Sein",
    licenseNo: "G(YGN)-0078",
    language: "English/Japanese",
    address: "No.7, Phonegyi Rd, Insein Tsp, Ygn.",
    phone: "",
  },
  {
    no: "79",
    name: "Daw Shwe Yi Min Han",
    licenseNo: "G(YGN)-0079",
    language: "English/Japanese/French",
    address: "NO-290/R, U Waiksaya St, Kamayut Ysp, Ygn.",
    phone: "",
  },
  {
    no: "80",
    name: "U Yin Naing Tun",
    licenseNo: "G(YGN)-0080",
    language: "English/German",
    address: "NO-290/R, U Waiksaya St, Kamayut Ysp, Ygn.",
    phone: "223817",
  },
  {
    no: "81",
    name: "Daw Ni Ni Khat",
    licenseNo: "G(YGN)-0081",
    language: "English",
    address: "No(235)5 Fl, Nguwah St, Ahlone Tsp, Ygn.",
    phone: "",
  },
  {
    no: "82",
    name: "Daw Aye Aye Thant",
    licenseNo: "G(YGN)-0082",
    language: "French",
    address: "No(6)GEC shop, (11)Qr, S/Okkalapa Tsp, Ygn.",
    phone: "9262570029",
  },
  {
    no: "83",
    name: "U Myo Thant",
    licenseNo: "G(YGN)-0083",
    language: "English",
    address: "Bld;124-3-Flr/A, San Yeik Nyein , Kamayut Tsp, Ygn.",
    phone: "95060825",
  },
  {
    no: "84",
    name: "U Thu Yein Tun Maw",
    licenseNo: "G(YGN)-0084",
    language: "English",
    address: "No.129, 43 St, Botathaung Tsp, Ygn.",
    phone: "95177977",
  },
  {
    no: "85",
    name: "U Kyaw Bo Thar",
    licenseNo: "G(YGN)-0085",
    language: "English/French",
    address: "No(20), Bldg 1, 2nd Fl, 4 Qr, N/Dagon Tsp, Ygn.",
    phone: "",
  },
  {
    no: "86",
    name: "Daw Khin Than Than Myat",
    licenseNo: "G(YGN)-0086",
    language: "English",
    address: "No.535, Mingyi St, Insein Tsp, Ygn.",
    phone: "",
  },
  {
    no: "87",
    name: "Daw Tin Htay Naing",
    licenseNo: "G(YGN)-0087",
    language: "English/Japanese",
    address: "No.99, 2nd fl, 51 St, 1 Qr, Puzundaung Tsp, Ygn.",
    phone: "",
  },
  {
    no: "88",
    name: "U San Win",
    licenseNo: "G(YGN)-0088",
    language: "English",
    address: "Bldg.10, Rm.30/b, Yawmimgyi St, Dagon Tsp, Ygn.",
    phone: "",
  },
  {
    no: "89",
    name: "Daw Khin Myo Myat",
    licenseNo: "G(YGN)-0089",
    language: "English",
    address: "No.52, Airport Yeikthar St, 10-mile, Insein Tsp, Ygn.",
    phone: "",
  },
  {
    no: "90",
    name: "U Khon Aung Zaw Min",
    licenseNo: "G(YGN)-0090",
    language: "English",
    address: "No.102/ B 4, Myintar Yeikmon Housing, Tamwe Tsp, Ygn.",
    phone: "",
  },
  {
    no: "91",
    name: "U Soe Min Aung",
    licenseNo: "G(YGN)-0091",
    language: "Thai",
    address: "No.78, 2nd Fl, Nanthar St, Ahlone Tsp, Ygn.",
    phone: "9451517878",
  },
  {
    no: "92",
    name: "U Tun Tun Oo",
    licenseNo: "G(YGN)-0092",
    language: "Japanese/Spanish",
    address: "No-290, Aung Khaymar St, 2-Qr, Mayangone Tsp, Ygn.",
    phone: "925010739",
  },
  {
    no: "93",
    name: "U Han Nyunt",
    licenseNo: "G(YGN)-0093",
    language: "English/Japanese",
    address: "No.420,Nweni-2st,Gayi-Qr,N/OkkalapaTsp,Ygn.",
    phone: "9450022538",
  },
  {
    no: "94",
    name: "U Tin Mg Mg",
    licenseNo: "G(YGN)-0094",
    language: "English/Japanese",
    address: "Bldg.8, Rm18,Pyiyeikmon Housing,Pyiyeikmon St-8,Qr,KamayutTsp,Ygn.",
    phone: "",
  },
  {
    no: "95",
    name: "Daw Khin Moe Win",
    licenseNo: "G(YGN)-0095",
    language: "English/Japanese",
    address: "No.162, 33 St, Kyauktada Tsp, Ygn.",
    phone: "",
  },
  {
    no: "96",
    name: "U Thet Zaw",
    licenseNo: "G(YGN)-0096",
    language: "English/German/Russian",
    address: "No.65/9, Baho St, 3 Qr, S/Okkalapa Tsp.Ygn.",
    phone: "",
  },
  {
    no: "97",
    name: "U Khin Mg Myint",
    licenseNo: "G(YGN)-0097",
    language: "English/Japanese",
    address: "No.59, Rm.3, Zayawati St, Sanchaung Tsp. Ygn.",
    phone: "95162001",
  },
  {
    no: "98",
    name: "Daw Tin Hnin Mar",
    licenseNo: "G(YGN)-0098",
    language: "Japanese",
    address: "No(3)1st Fl, S/Sayasan, Bahan Tsp, Ygn.",
    phone: "97306531",
  },
  {
    no: "99",
    name: "Daw Shi Hlaing Eain",
    licenseNo: "G(YGN)-0099",
    language: "Chinese",
    address: "No.129, 1st Fl, 14 St, Lanmadaw Tsp, Ygn.",
    phone: "0943194625/09795811085",
  },
  {
    no: "100",
    name: "U Ye Myat Kyaw",
    licenseNo: "G(YGN)-0100",
    language: "English/Thai",
    address: "No.7/Ka, Dawna St, East Ywama , Insein Tsp, Ygn.",
    phone: "504307",
  }
];


export const metadata = {
  title: "Regional Tour Guides",
  description: "Regional tour guides licensed by the Ministry of Hotels and Tourism, Myanmar."
};

export default function RegionalTourGuide() {
  return (
    <div className={styles.pageContainer}>
      <BannerSection imageUrl="/assets/images/cover-images/55.jpg" altText="national tour guide cover photo" />
      <Breadcrumb
        items={[
          { label: "Home", href: "/", icon: faHome },
          { label: "Regional Tour Guides", active: true }
        ]}
      />
      <div className={styles.container}>
        <h1 className={styles.pageTitle}>Regional Tour Guides</h1>
        {/* <p className={styles.paragraph}>နိုင်ငံတော်ခရီးသွားလမ်းပြများ၏ အချက်အလက်များကို ရှာဖွေနိုင်ပါသည်။</p> */}
        <div className={styles.tableResponsive}>
          <table className={styles.guideTable}>
            <thead>
              <tr>
                <th>No</th>
                <th>Name</th>
                <th>License No.</th>
                <th>Language</th>
                <th>Address</th>
                <th>Ph No.</th>
              </tr>
            </thead>
            <tbody>
              {tourGuides.map((guide, idx) => (
                <tr key={idx}>
                  <td>{guide.no}</td>
                  <td>{guide.name}</td>
                  <td>{guide.licenseNo}</td>
                  <td>{guide.language}</td>
                  <td>{guide.address}</td>
                  <td>{guide.phone}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}