import Breadcrumb from "../../../../components/Breadcrumb";
import BannerSection from "../../../../components/BannerSection";
import styles from "@/app/en/tour-guides/national-tour-guides/NationalTourGuides.module.css";
import { faHome } from "@fortawesome/free-solid-svg-icons";

const tourGuides = [
  {
    no: "1",
    name: "Daw Htay Htay Tin",
    licenseNo: "G-0001",
    licenseDate: "", 
    language: "English/French",
    address: "No-8/ka, Kaymarthi St, Michaungkan Region(3), Thingangyun Tsp, Ygn.",
    phone: "",
  },
  {
    no: "2",
    name: "U Kyaw Win Mg",
    licenseNo: "G-0005",
    licenseDate: "",
    language: "English/French",
    address: "No-18, Manahaye St, Mahlawgone Qr, Tamwe Tsp, Ygn.",
    phone: "",
  },
  {
    no: "3",
    name: "U Tin Tun",
    licenseNo: "G-0009",
    licenseDate: "",
    language: "English/French",
    address: "No-1, Pannyoema Bldg, Thidaraye (902) Qr, Chanmyatharsi Tsp, Mdy.",
    phone: "",
  },
  {
    no: "4",
    name: "Daw Rose Marthar",
    licenseNo: "G-0010",
    licenseDate: "",
    language: "English/Japanese",
    address: "No-69/5, Sanchaung St, N/Sanchaung Qr, Sanchaung Tsp, Ygn.",
    phone: "",
  },
  {
    no: "5",
    name: "U Aung Kyaw Lin",
    licenseNo: "G-0013",
    licenseDate: "",
    language: "English/Japanese",
    address: "No-65, Ayeyarwaddy St, Ahlone Tsp, Ygn.",
    phone: "",
  },
  {
    no: "6",
    name: "U Win Kyawe",
    licenseNo: "G-0014",
    licenseDate: "",
    language: "English/French",
    address: "No-96, Five Flr, Shan St, Sanchaung Tsp, Ygn.",
    phone: "",
  },
  {
    no: "7",
    name: "Daw Myint Myint Maw",
    licenseNo: "G-0017",
    licenseDate: "",
    language: "Chinese/French",
    address: "No-396, Lower Pazuntaung St, Pazuntaung Tsp, Ygn.",
    phone: "",
  },
  {
    no: "8",
    name: "Daw Toe Khin Khin",
    licenseNo: "G-0022",
    licenseDate: "",
    language: "English/Japanese",
    address: "No-203/23, East Yankin Tsp, Ygn.",
    phone: "",
  },
  {
    no: "9",
    name: "U Myat Wanna",
    licenseNo: "G-0024",
    licenseDate: "",
    language: "English",
    address: "Bldg-204, Rm.18, East Yankin Tsp, Ygn.",
    phone: "",
  },
  {
    no: "10",
    name: "Daw Tan Pate Lyan",
    licenseNo: "G-0027",
    licenseDate: "",
    language: "English/Japanese",
    address: "No.30, Lanmadaw Rd, Latha Tsp, Ygn.",
    phone: "",
  },
  {
    no: "11",
    name: "Daw Khin Khin Swe",
    licenseNo: "G-0028",
    licenseDate: "",
    language: "English/Japanese",
    address: "No.(30), 3-Flr, New Yaetarshae St, Bahan Tsp, Ygn.",
    phone: "95133146",
  },
  {
    no: "12",
    name: "U Thin New",
    licenseNo: "G-0030",
    licenseDate: "",
    language: "English/Japanese",
    address: "No.(554/c), Nant Tharkone Qtr, Insein Tsp., Ygn.",
    phone: "9430959731",
  },
  {
    no: "13",
    name: "Daw Mar Lar Lwin",
    licenseNo: "G-0035",
    licenseDate: "",
    language: "Japanese",
    address: "No.(277), Damayone Rd., (13)Qtr, Yankin Tsp, Ygn.",
    phone: "642136",
  },
  {
    no: "14",
    name: "U Htin Aung Kyi",
    licenseNo: "G-0037",
    licenseDate: "",
    language: "English/Italian",
    address: "No.19, Aung Thiri (4) St, 28-Qr, N/Dagon Tsp, Ygn.",
    phone: "578189",
  },
  {
    no: "15",
    name: "U Tin Khine",
    licenseNo: "G-0039",
    licenseDate: "",
    language: "Chinese/Japanese",
    address: "No.(64) 1StFl. 21 St. Latha Tsp, Ygn.",
    phone: "95102801",
  },
  {
    no: "16",
    name: "Daw Khin Myat Thu",
    licenseNo: "G-0045",
    licenseDate: "",
    language: "English",
    address: "No.(55/4), Boyarnyunt St. Dagon Tsp, Ygn.",
    phone: "95102801",
  },
  {
    no: "17",
    name: "U Soe Myint",
    licenseNo: "G-0050",
    licenseDate: "",
    language: "English/French",
    address: "Bldg.(9), 4 Flr;®, Danatheikdi St, (2)Qr. Mayangone Tsp. Ygn.",
    phone: "95117786",
  },
  {
    no: "18",
    name: "Daw Soe Nyunt Kyine",
    licenseNo: "G-0052",
    licenseDate: "",
    language: "English",
    address: "No.(118) Kyun Shwemyaing Lane (2), Thingangyun Tsp. Ygn.",
    phone: "95155062",
  },
  {
    no: "19",
    name: "Daw Yi Yi Han",
    licenseNo: "G-0059",
    licenseDate: "",
    language: "English",
    address: "No.(55/2)(A) (14)St. Lanmadaw Tsp. Ygn.",
    phone: "1210828",
  },
  {
    no: "20",
    name: "U Kyaw Soe Myint",
    licenseNo: "G-0060",
    licenseDate: "",
    language: "English/French",
    address: "No(8/c) Maykha St. Mayangone Tsp. Ygn.",
    phone: "",
  },
   {
    no: "21",
    name: "Daw Kyi Kyi Aye",
    licenseNo: "G-0062",
    licenseDate: "",
    language: "English",
    address: "No.(43) Myintmo St. Sanchaung Tsp.Ygn.",
    phone: "95144006",
  },
  {
    no: "22",
    name: "Daw Khin Thein Win",
    licenseNo: "G-0070",
    licenseDate: "",
    language: "English/French",
    address: "Bldg.(L/406) No.47, Baho St. Manaw Hayi Yeikthar. Ahlone Tsp. Ygn.",
    phone: "95155859",
  },
  {
    no: "23",
    name: "U Win Myint Saw Maine",
    licenseNo: "G-0077",
    licenseDate: "",
    language: "English",
    address: "No(64). Rm F/2. Ahwaiyar Housing, Myintar Nyunt Qr, Tamwe Tsp.Ygn.",
    phone: "95115625",
  },
  {
    no: "24",
    name: "Daw San San Tun",
    licenseNo: "G-0079",
    licenseDate: "",
    language: "English/Italian",
    address: "Bldg.(4)Rm 11. Link St., Shwegondine, Bahan Tsp. Ygn.",
    phone: "",
  },
  {
    no: "25",
    name: "U Mg Mg Than",
    licenseNo: "G-0081",
    licenseDate: "",
    language: "English",
    address: "No(19/B) Nawaday St., Yawmimgyi Qr, Dagon Tsp, Ygn.",
    phone: "9420020020",
  },
  {
    no: "26",
    name: "U Nyi Nyi Chit Hla",
    licenseNo: "G-0083",
    licenseDate: "",
    language: "English/Japanese",
    address: "No.(53) Yaekyaw St. Puzundaung Tsp. Ygn.",
    phone: "389045",
  },
  {
    no: "27",
    name: "U Kyaw Oo",
    licenseNo: "G-0084",
    licenseDate: "",
    language: "English/French",
    address: "No(36/556) Peral St. N/Dagon Myothit Tsp. Ygn.",
    phone: "",
  },
  {
    no: "28",
    name: "U Aung Zaw Myint",
    licenseNo: "G-0090",
    licenseDate: "",
    language: "English/Spanish",
    address: "No(83)Myawutyee St. (29)Qr. Thuwunna, Thingangyun Tsp. Ygn.",
    phone: "580076",
  },
  {
    no: "29",
    name: "U Myat Tun",
    licenseNo: "G-0091",
    licenseDate: "",
    language: "English",
    address: "No(141/2) Meedone St. Thingangyun Tsp. Ygn.",
    phone: "92047902",
  },
  {
    no: "30",
    name: "U Phone Mg",
    licenseNo: "G-0093",
    licenseDate: "",
    language: "English/French",
    address: "Bldg (30) Rm. (15) Thunandar St. (10)Qr. Hlaing Tsp. Ygn.",
    phone: "95132748",
  },
    {
    no: "31",
    name: "U Myo Nyunt",
    licenseNo: "G-0095",
    licenseDate: "",
    language: "English",
    address: "No(325) Naykyar St. (45)Qr. N/Dagon Tsp. Ygn.",
    phone: "95132748",
  },
  {
    no: "32",
    name: "Daw Cho Cho Myint",
    licenseNo: "G-0096",
    licenseDate: "",
    language: "English",
    address: "No(141/2) Meedon St. Thingangyun Tsp.Ygn.",
    phone: "95401160",
  },
  {
    no: "33",
    name: "U Tin Naing (&) Khin Kyaw",
    licenseNo: "G-0097",
    licenseDate: "",
    language: "French",
    address: "No(134)(42)St. (8)Qr. Botathaung Tsp. Ygn.",
    phone: "95163559",
  },
  {
    no: "34",
    name: "U Mya Win Mg",
    licenseNo: "G-0098",
    licenseDate: "",
    language: "English/German",
    address: "No.(5a/557) Maydarwi Rd. (Salein)Qr. N/Okkalapa Tsp. Ygn.",
    phone: "95088768",
  },
  {
    no: "35",
    name: "U Cho Win",
    licenseNo: "G-0099",
    licenseDate: "",
    language: "Japanese",
    address: "No.(57)(41)St, Botathaung Tsp. Ygn.",
    phone: "01382795/95152460",
  },
  {
    no: "36",
    name: "Daw Kyi Kyi Sein",
    licenseNo: "G-0101",
    licenseDate: "",
    language: "French",
    address: "No(19/D) Chit Yeikmon St. Ygn-Insein Rd. Mayangone Tsp. Ygn.",
    phone: "",
  },
  {
    no: "37",
    name: "U Hla Myint",
    licenseNo: "G-0107",
    licenseDate: "",
    language: "English",
    address: "No(10/kha) Hledan (7) St. (3)Qr. Kamayut Tsp. Ygn.",
    phone: "95169788",
  },
  {
    no: "38",
    name: "Daw Khin Thida Aye",
    licenseNo: "G-0111",
    licenseDate: "",
    language: "English/Spanish",
    address: "No(704/B) Peral Condo, Kabaraye Pagoda Rd. Bahan Tsp. Ygn.",
    phone: "",
  },
  {
    no: "39",
    name: "Daw Yin Yin Sein",
    licenseNo: "G-0112",
    licenseDate: "",
    language: "German",
    address: "No.(12) Zizawar St. Ngwe Kyaryan Yeikthar, S/Okkalpa Tsp. Ygn.",
    phone: "9421755320",
  },
  {
    no: "40",
    name: "U Soe Win",
    licenseNo: "G-0113",
    licenseDate: "",
    language: "English/Chinese",
    address: "No(405/a) Myintzu St. (5)Qr. E/Dagon Tsp. Ygn.",
    phone: "933154960",
  },
  {
    no: "41",
    name: "U Than Tun Aung (&) Ba Nyein",
    licenseNo: "G-0116",
    licenseDate: "",
    language: "English/Italian",
    address: "No(5/74) Aung Tayza St. Manyangon Tsp. Ygn.",
    phone: "",
  },
  {
    no: "42",
    name: "Daw PS Kalar Ni Khine",
    licenseNo: "G-0125",
    licenseDate: "",
    language: "German",
    address: "No-25, Shwe Hnini Si Lane(3), 5-Qr, Mayangone Tsp. Ygn.",
    phone: "",
  },
  {
    no: "43",
    name: "U Saw Hla Chit",
    licenseNo: "G-0130",
    licenseDate: "",
    language: "Japanese",
    address: "No(908). (1)St. E/gyoegone Insein Tsp. Ygn.",
    phone: "95177628",
  },
  {
    no: "44",
    name: "U Myo Win",
    licenseNo: "G-0136",
    licenseDate: "",
    language: "English",
    address: "NO-18/5/B, Maharzaya St, Yae Kyaw, Pazuntaung Tsp, Ygn.",
    phone: "1294777",
  },
  {
    no: "45",
    name: "U Zaw Myint",
    licenseNo: "G-0137",
    licenseDate: "",
    language: "English",
    address: "No(28/A/3) Kokkine Swimming Pool St, Bahan Tsp, Ygn.",
    phone: "",
  },
  {
    no: "46",
    name: "Daw Tin Pyone Khin",
    licenseNo: "G-0139",
    licenseDate: "",
    language: "English",
    address: "No.(A/302) Peral Center, Bahan Tsp. Ygn.",
    phone: "",
  },
  {
    no: "47",
    name: "U Moe Aung Lwin",
    licenseNo: "G-0150",
    licenseDate: "",
    language: "English",
    address: "Bldg-5 Rm.2/ka. Thiri St. Sanchaung Tsp. Ygn.",
    phone: "973234841",
  },
  {
    no: "48",
    name: "Daw Chaw Mywar Win",
    licenseNo: "G-0157",
    licenseDate: "",
    language: "English",
    address: "Sane Tone St. Shwe Kyetyet Village, Ahmarapura Tsp. Mdy.",
    phone: "534003",
  },
  {
    no: "49",
    name: "U Nyi Nyi Khine",
    licenseNo: "G-0163",
    licenseDate: "",
    language: "English",
    address: "No-25 Shwe Hninsi(3), 5-St.Qr. Mayangone Tsp. Ygn.",
    phone: "",
  },
  {
    no: "50",
    name: "Daw Thet Thet Naing",
    licenseNo: "G-0165",
    licenseDate: "",
    language: "English/French",
    address: "No-8. Thuzitat St. Thingangyun Tsp. Ygn.",
    phone: "",
  },
   {
    no: "51",
    name: "Daw Yin Nyeo Tin",
    licenseNo: "G-0167",
    licenseDate: "",
    language: "English",
    address: "No-36 Kyaung Gone St. Sanchaung Tsp. Ygn.",
    phone: "95175646",
  },
  {
    no: "52",
    name: "Daw May May Thet",
    licenseNo: "G-0169",
    licenseDate: "",
    language: "English/French",
    address: "Bldg-6 Rm.(4) Than Thumar St. S/Okkalapa Tsp. Ygn.",
    phone: "",
  },
  {
    no: "53",
    name: "Daw Kye Kye Mar",
    licenseNo: "G-0173",
    licenseDate: "",
    language: "English",
    address: "No.12/kha, U Waisara Housing, Dagon Tsp, Ygn.",
    phone: "",
  },
  {
    no: "54",
    name: "U Ye Lwin",
    licenseNo: "G-0177",
    licenseDate: "",
    language: "Chinese",
    address: "No(173/ka) Myaung Gyi St, Yaekyaw, Puzuntaung Tsp. Ygn.",
    phone: "01296275/0973057919",
  },
  {
    no: "55",
    name: "Daw Nan Loung Khan",
    licenseNo: "G-0178",
    licenseDate: "",
    language: "German",
    address: "Bldg(22)Rm.(22) Hlaing Tsp, Ygn.",
    phone: "95149371",
  },
  {
    no: "56",
    name: "U Han Htet Aung",
    licenseNo: "G-0183",
    licenseDate: "",
    language: "English",
    address: "No(16)F-Shwe Bo St/Tamwe Tsp, Ygn.",
    phone: "",
  },
  {
    no: "57",
    name: "U Thant Zaw Nyien",
    licenseNo: "G-0184",
    licenseDate: "",
    language: "English",
    address: "No.(27)Yandana Mon(3)St. 5-Qr. Hlaing Tsp. Ygn.",
    phone: "",
  },
  {
    no: "58",
    name: "U Zaw Min",
    licenseNo: "G-0196",
    licenseDate: "",
    language: "English",
    address: "No(6),Aungmyay Thar Qr. Nyaung Oo,Mdy.",
    phone: "",
  },
  {
    no: "59",
    name: "Daw Khin May Phyu",
    licenseNo: "G-0197",
    licenseDate: "",
    language: "Japanese",
    address: "No(3/B) Near Sin Min Market. Ahlone Tsp, Ygn.",
    phone: "",
  },
  {
    no: "60",
    name: "U Mg Mg",
    licenseNo: "G-0199",
    licenseDate: "",
    language: "English/Japanese",
    address: "Bldg(c) No(54) Bonyar Nyunt St. Dagon Tsp. Ygn.",
    phone: "",
  },
  {
    no: "61",
    name: "U Sein Win",
    licenseNo: "G-0201",
    licenseDate: "",
    language: "English/French",
    address: "No-304/D/1, Bahan Tsp, Ygn.",
    phone: "",
  },
  {
    no: "62",
    name: "Daw Khin Than Nwe",
    licenseNo: "G-0202",
    licenseDate: "",
    language: "Japanese",
    address: "No(27/B-3) Pathein St. Sangaung Tsp. Ygn.",
    phone: "95183114",
  },
  {
    no: "63",
    name: "U Win Myint",
    licenseNo: "G-0203",
    licenseDate: "",
    language: "English/French",
    address: "No.(10)Khaymarthi St. Thingangyun Tsp.Ygn.",
    phone: "09926253 629139",
  },
  {
    no: "64",
    name: "U Myint Oo",
    licenseNo: "G-0207",
    licenseDate: "",
    language: "English/Thai",
    address: "Bldg 2- Rm.205, Kamayut Tsp. Ygn.",
    phone: "570611",
  },
  {
    no: "65",
    name: "U Saw Chit Oo",
    licenseNo: "G-0210",
    licenseDate: "",
    language: "English",
    address: "No.52, Sadan St. Ahlone Tsp. Ygn.",
    phone: "",
  },
  {
    no: "66",
    name: "U Hla Myint",
    licenseNo: "G-0212",
    licenseDate: "",
    language: "German",
    address: "No-47, 3 Fl, Kyaukmyuang, Tamwe Tsp. Ygn.",
    phone: "",
  },
  {
    no: "67",
    name: "U Tan D Soe",
    licenseNo: "G-0215",
    licenseDate: "",
    language: "English/Japanese",
    address: "No.31/28, Aungmingalar St, Phawkan Qr. Insein Tsp. Ygn.",
    phone: "",
  },
  {
    no: "68",
    name: "U Bin Sin Soe Myint",
    licenseNo: "G-0216",
    licenseDate: "",
    language: "English",
    address: "No.5, Masoeyein kyaung St, 9-mile, Mayangone Tsp. Ygn.",
    phone: "646067",
  },
  {
    no: "69",
    name: "U Sai Thein Lwin",
    licenseNo: "G-0217",
    licenseDate: "",
    language: "Japanese",
    address: "No.158, 79 St. Bet. 30x31, Mdy.",
    phone: "",
  },
  {
    no: "70",
    name: "U Sai Lwin",
    licenseNo: "G-0220",
    licenseDate: "",
    language: "English/Thai",
    address: "No(305), Maekhaung Qr, Tarchileik, Shan State.",
    phone: "232709",
  },
  {
    no: "71",
    name: "Daw Zaka War Soe",
    licenseNo: "G-0221",
    licenseDate: "",
    language: "English/Thai",
    address: "Bldg.2, Rm.205- Aungmyay Tharsi Housing, Kamayut Tsp. Ygn.",
    phone: "",
  },
  {
    no: "72",
    name: "U Tin Aung Moe",
    licenseNo: "G-0223",
    licenseDate: "",
    language: "English",
    address: "No.29, Sanchaung St. Sanchaung Tsp, Ygn.",
    phone: "",
  },
  {
    no: "73",
    name: "Daw Maw Maw Aung",
    licenseNo: "G-0224",
    licenseDate: "",
    language: "English",
    address: "No.(F/120), Khayae St, Bagan, Mdy.",
    phone: "",
  },
  {
    no: "74",
    name: "U Win Tin",
    licenseNo: "G-0229",
    licenseDate: "",
    language: "Japanese",
    address: "No54/A, 94 St. Mingalar Taung Nyunt Tsp, Ygn.",
    phone: "",
  },
  {
    no: "75",
    name: "U Hla Win",
    licenseNo: "G-0230",
    licenseDate: "",
    language: "English/Chinese",
    address: "No.20, Upper FL, 24 St, Lathar Tsp, Ygn.",
    phone: "95116459",
  },
  {
    no: "76",
    name: "U Aung Kyaw",
    licenseNo: "G-0234",
    licenseDate: "",
    language: "Japanese",
    address: "No(3/164) Kangaw St. Waibargi Myothit, N/Okkalapla Tsp. Ygn.",
    phone: "",
  },
  {
    no: "77",
    name: "U Aung Aung Kyaw",
    licenseNo: "G-0235",
    licenseDate: "",
    language: "English",
    address: "No-2/B/840, Muditar Condo-2, 16-Qr, Insein Tsp, Ygn.",
    phone: "",
  },
  {
    no: "78",
    name: "U Hla Mg",
    licenseNo: "G-0236",
    licenseDate: "",
    language: "English",
    address: "No(8) Upper Puzundaung St. Mingalar Taungnyut Tsp, Ygn.",
    phone: "",
  },
  {
    no: "79",
    name: "U Tin Moe",
    licenseNo: "G-0239",
    licenseDate: "",
    language: "English",
    address: "No(81)32 St, Ground Fl, Pabedan Tsp, Ygn.",
    phone: "",
  },
  {
    no: "80",
    name: "U Mya Lwin",
    licenseNo: "G-0241",
    licenseDate: "",
    language: "Japanese",
    address: "No.37, Thantadar St, Sanchaung Tsp, Ygn.",
    phone: "",
  },
  {
    no: "81",
    name: "Daw Moe Moe Thein",
    licenseNo: "G-0243",
    licenseDate: "",
    language: "English",
    address: "No.E/4, Shwe Yinmar St, Kamaryut Tsp, Ygn.",
    phone: "",
  },
  {
    no: "82",
    name: "Daw Yi Yi Thein",
    licenseNo: "G-0247",
    licenseDate: "",
    language: "English",
    address: "No.206/26, E/Yankin, Yankin Tsp, Ygn.",
    phone: "",
  },
  {
    no: "83",
    name: "U Tin Mg Hlaing",
    licenseNo: "G-0254",
    licenseDate: "",
    language: "English/Japanese",
    address: "Bldg 10, Rm.11, Shwe Onphin Housing, 5 Qr, W/Yankin Tsp, Ygn.",
    phone: "",
  },
  {
    no: "84",
    name: "Daw Khin Nwe Sein",
    licenseNo: "G-0255",
    licenseDate: "",
    language: "English/French",
    address: "No.7, Phonegyi Rd, Insein Tsp, Ygn.",
    phone: "",
  },
  {
    no: "85",
    name: "Daw Shwe Yi Min Han",
    licenseNo: "G-0256",
    licenseDate: "",
    language: "English/Japanese/French",
    address: "NO-290/R, U Waiksaya St, Kamayut Ysp, Ygn.",
    phone: "",
  },
  {
    no: "86",
    name: "U Yin Naing Tun",
    licenseNo: "G-0257",
    licenseDate: "",
    language: "English/German",
    address: "NO-290/R, U Waiksaya St, Kamayut Ysp, Ygn.",
    phone: "223817",
  },
  {
    no: "87",
    name: "Daw Ni Ni Khat",
    licenseNo: "G-0265",
    licenseDate: "",
    language: "English",
    address: "No(235)5 Fl, Nguwah St, Ahlone Tsp, Ygn.",
    phone: "",
  },
  {
    no: "88",
    name: "Daw Aye Aye Thant",
    licenseNo: "G-0270",
    licenseDate: "",
    language: "French",
    address: "No(6)GEC shop, (11)Qr, S/Okkalpa Tsp, Ygn.",
    phone: "9262570029",
  },
  {
    no: "89",
    name: "U Myo Thant",
    licenseNo: "G-0271",
    licenseDate: "",
    language: "English",
    address: "Bld;124-3-Flr/A, San Yeik Nyein, Kamayut Tsp, Ygn.",
    phone: "95060825",
  },
  {
    no: "90",
    name: "U Thu Yein Tun Maw",
    licenseNo: "G-0273",
    licenseDate: "",
    language: "English",
    address: "No.129, 43 St, Botathaung Tsp, Ygn.",
    phone: "95177977",
  },
  {
    no: "91",
    name: "U Kyaw Bo Thar",
    licenseNo: "G-0274",
    licenseDate: "",
    language: "English/French",
    address: "No(20), Bldg 1, 2nd Fl, 4 Qr, N/Dagon Tsp, Ygn.",
    phone: "",
  },
  {
    no: "92",
    name: "Daw Khin Than Than Myat",
    licenseNo: "G-0275",
    licenseDate: "",
    language: "English",
    address: "No.535, Mingyi St, Insein Tsp, Ygn.",
    phone: "",
  },
  {
    no: "93",
    name: "Daw Tin Htay Naing",
    licenseNo: "G-0276",
    licenseDate: "",
    language: "English/Japanese",
    address: "No.99, 2nd fl, 51 St, 1 Qr, Puzundaung Tsp, Ygn.",
    phone: "",
  },
  {
    no: "94",
    name: "U San Win",
    licenseNo: "G-0277",
    licenseDate: "",
    language: "English",
    address: "Bldg.10, Rm.30/b, Yawmimgyi St, Dagon Tsp, Ygn.",
    phone: "",
  },
  {
    no: "95",
    name: "Daw Khin Myo Myat",
    licenseNo: "G-0279",
    licenseDate: "",
    language: "English",
    address: "No.52, Airport Yeikthar St, 10-mile, Insein Tsp, Ygn.",
    phone: "",
  },
  {
    no: "96",
    name: "U Khon Aung Zaw Min",
    licenseNo: "G-0281",
    licenseDate: "",
    language: "English",
    address: "No.102/B 4, Myintar Yeikmon Housing, Tamwe Tsp, Ygn.",
    phone: "",
  },
  {
    no: "97",
    name: "U Soe Min Aung",
    licenseNo: "G-0282",
    licenseDate: "",
    language: "Thai",
    address: "No.78, 2nd Fl, Nanthar St, Ahlone Tsp, Ygn.",
    phone: "9451517878",
  },
  {
    no: "98",
    name: "U Tun Tun Oo",
    licenseNo: "G-0285",
    licenseDate: "",
    language: "Japanese/Spanish",
    address: "No-290, Aung Khaymar St, 2-Qr, Mayangone Tsp, Ygn.",
    phone: "925010739",
  },
  {
    no: "99",
    name: "U Han Nyunt",
    licenseNo: "G-0287",
    licenseDate: "",
    language: "English/Japanese",
    address: "No.420, Nweni-2st, Gayi-Qr, N/Okkalapa Tsp, Ygn.",
    phone: "9450022538",
  },
  {
    no: "100",
    name: "U Tin Mg Mg",
    licenseNo: "G-0291",
    licenseDate: "",
    language: "English/Japanese",
    address: "No.55/52-B, Insein St, 9 Qr, Hlaing Tsp, Ygn.",
    phone: "",
  },
   {
    no: "101",
    name: "U Phyo Wai Win",
    licenseNo: "G-0312",
    licenseDate: "",
    language: "English",
    address: "Daw ChoYe, Aungmingalar, Nyaung Oo, Mdy.",
    phone: "",
  },
  {
    no: "102",
    name: "Daw Khin Moe Win",
    licenseNo: "G-0315",
    licenseDate: "",
    language: "English/Japanese",
    address: "No.162, 33 St, Kyauktada Tsp, Ygn.",
    phone: "",
  },
  {
    no: "103",
    name: "U Thet Zaw",
    licenseNo: "G-0316",
    licenseDate: "",
    language: "English/German/Russian",
    address: "No.65/9, Baho St, 3 Qr, S/Okkalapa Tsp.Ygn.",
    phone: "",
  },
  {
    no: "104",
    name: "U Khin Mg Myint",
    licenseNo: "G-0318",
    licenseDate: "",
    language: "English/Japanese",
    address: "No.59, Rm.3, Zayawati St, Sanchaung Tsp. Ygn.",
    phone: "95162001",
  },
  {
    no: "105",
    name: "Daw Tin Hnin Mar",
    licenseNo: "G-0320",
    licenseDate: "",
    language: "Japanese",
    address: "No(3)1st Fl, S/Sayasan, Bahan Tsp, Ygn.",
    phone: "97306531",
  },
  {
    no: "106",
    name: "Daw Shi Hlaing Eain",
    licenseNo: "G-0322",
    licenseDate: "",
    language: "Chinese",
    address: "No.129, 1st Fl, 14 St, Lanmadaw Tsp, Ygn.",
    phone: "0943194625/09795811085",
  },
  {
    no: "107",
    name: "U Ye Myat Kyaw",
    licenseNo: "G-0323",
    licenseDate: "",
    language: "English/Thai",
    address: "No.7/Ka, Dawna St, East Ywama, Insein Tsp, Ygn.",
    phone: "504307",
  },
  {
    no: "108",
    name: "U Phone Zaw",
    licenseNo: "G-0328",
    licenseDate: "",
    language: "English",
    address: "Bldg.64 Rm.A-2/B, Thiri Haymar St, Zawana Qr, Thingangyun Tsp, Ygn.",
    phone: "95001015",
  },
  {
    no: "109",
    name: "U Tin Myint",
    licenseNo: "G-0332",
    licenseDate: "",
    language: "English",
    address: "No-18/H, Yadanar Mying St, 1-Qr, Sanyeik Nyein ,Kamayut Tsp, Ygn.",
    phone: "",
  },
  {
    no: "110",
    name: "Daw Mi Mi Lat",
    licenseNo: "G-0338",
    licenseDate: "",
    language: "German",
    address: "No(D-48)-4 St, Kywesekan, Mdy.",
    phone: "",
  },
  {
    no: "111",
    name: "Daw Aein Nan May",
    licenseNo: "G-0339",
    licenseDate: "",
    language: "French",
    address: "Bldg.49, Rm.19, Bahosi Yeik Thar, Lanmadaw Tsp, Ygn.",
    phone: "95049763",
  },
  {
    no: "112",
    name: "U Htay Aung",
    licenseNo: "G-0352",
    licenseDate: "",
    language: "English",
    address: "Bldg.175, 301, Bagoda Rd, 5 Qr, Kamaryut Tsp. Ygn.",
    phone: "9250375580",
  },
  {
    no: "113",
    name: "Daw Ni Ni Myint",
    licenseNo: "G-0353",
    licenseDate: "",
    language: "English/Chinese/French",
    address: "No.26, 1st FL, 24 St, Latha Tsp, Ygn.",
    phone: "",
  },
  {
    no: "114",
    name: "U Ba Hein",
    licenseNo: "G-0362",
    licenseDate: "",
    language: "English",
    address: "No.1193,13 St, 6 Qr, S/Okkalapa Tsp,Ygn.",
    phone: "95110713",
  },
  {
    no: "115",
    name: "U Zaw Moe Than",
    licenseNo: "G-0363",
    licenseDate: "",
    language: "English",
    address: "No.20, Rm.6/B, Maupin St, Sanchaung Tsp. Ygn.",
    phone: "95160006",
  },
  {
    no: "116",
    name: "Daw Khin Myat Maw",
    licenseNo: "G-0364",
    licenseDate: "",
    language: "English",
    address: "Bldg 262, Rm-14,(2)Qr, Yankin Tsp, Ygn.",
    phone: "95084346",
  },
  {
    no: "117",
    name: "Daw Khin Myo Wai",
    licenseNo: "G-0366",
    licenseDate: "",
    language: "English",
    address: "No.159, Sabai Chan 3 St, 11 Qr, Hlaing Tsp, Ygn.",
    phone: "95197653",
  },
  {
    no: "118",
    name: "U Jaw Ni",
    licenseNo: "G-0380",
    licenseDate: "",
    language: "English",
    address: "Bldg.4, Rm.505, Thitsar Garden Housing, 8 Qr, 3 St, S/Okkalapa Tsp, Ygn.",
    phone: "95122432",
  },
  {
    no: "119",
    name: "U Lwin Ohm",
    licenseNo: "G-0386",
    licenseDate: "",
    language: "English/Japanese",
    address: "No.34, Ground Fl, 22 St, Latha Tsp, Ygn.",
    phone: "95117453",
  },
  {
    no: "120",
    name: "U Myo Win",
    licenseNo: "G-0390",
    licenseDate: "",
    language: "English/Russian",
    address: "No.1302, 12 St, Banyardala Qr, Dala Tsp,Ygn.",
    phone: "",
  },
  {
    no: "121",
    name: "U Myo Htut Oo",
    licenseNo: "",
    licenseDate: "",
    language: "English/Korean",
    address: "No.739, Hlaing Thiri 1 St, 31 Qr, N/Dagon Tsp, Ygn.",
    phone: "95000461",
  },
  {
    no: "122",
    name: "U Tin Myat",
    licenseNo: "G-0397",
    licenseDate: "",
    language: "English",
    address: "No.124, Ka/6, Sachaung St, Sachaung Tsp, Ygn.",
    phone: "",
  },
  {
    no: "123",
    name: "U Sai Wan Sone",
    licenseNo: "G-0403",
    licenseDate: "",
    language: "Eng/Thai/Spni",
    address: "No.145/L,Rm-2nd Fl, Thiri Yeikthar, Ahlone Tsp, Ygn.",
    phone: "95007021/01539224",
  },
  {
    no: "124",
    name: "U Kyaw Moe Win",
    licenseNo: "G-0408",
    licenseDate: "",
    language: "English/German",
    address: "No.71, Thamainbayan St, Tamwegyi,(Ka/8) Qr, Tamwe Tsp, Ygn.",
    phone: "",
  },
  {
    no: "125",
    name: "U Than Naing",
    licenseNo: "G-0416",
    licenseDate: "",
    language: "English",
    address: "No.7/ Natchaung, Tamwe Tsp, Ygn.",
    phone: "95119958",
  },
  {
    no: "126",
    name: "U Mg Mg Kyi",
    licenseNo: "G-0422",
    licenseDate: "",
    language: "German",
    address: "No.161, Khine Shwewah St, Hledan ,Kamaryut Tsp, Ygn.",
    phone: "539224",
  },
  {
    no: "127",
    name: "U Min Myint Soe",
    licenseNo: "G-0425",
    licenseDate: "",
    language: "English/Japanese",
    address: "No.337/ Bouang kyaw St, Kyauktada Tsp, Ygn.",
    phone: "",
  },
  {
    no: "128",
    name: "Daw Sandar Khin",
    licenseNo: "G-0426",
    licenseDate: "",
    language: "English",
    address: "No.1139, Malarwine St, Myintar Nyunt Qr, Tamwe Tsp, Ygn.",
    phone: "",
  },
  {
    no: "129",
    name: "U Lay Mg",
    licenseNo: "G-0428",
    licenseDate: "",
    language: "English",
    address: "No.12/ Naythuyein St, Bahan Tsp, Ygn.",
    phone: "725414",
  },
  {
    no: "130",
    name: "U Yan Aung",
    licenseNo: "G-0431",
    licenseDate: "",
    language: "English/Spanish",
    address: "No.82, Sipin St, 24 Qr, S/Dagon Tsp, Ygn.",
    phone: "95172093",
  },
  {
    no: "131",
    name: "U Hla Baw",
    licenseNo: "G-0442",
    licenseDate: "",
    language: "Japanese",
    address: "No.62/A-4, Yawmimgyi St, Dagon Tsp, Ygn.",
    phone: "",
  },
  {
    no: "132",
    name: "U Than Naing",
    licenseNo: "G-0453",
    licenseDate: "",
    language: "Japanese",
    address: "No.15/5/ka, Chinsawpu Pagoda St, Sanchaung Tsp, Ygn.",
    phone: "9420055233",
  },
  {
    no: "133",
    name: "U Than Htike Aung",
    licenseNo: "G-0456",
    licenseDate: "",
    language: "English/French",
    address: "No.4, Minoo St, Sanchaung Tsp, Ygn.",
    phone: "",
  },
  {
    no: "134",
    name: "U Htay Win",
    licenseNo: "G-0459",
    licenseDate: "",
    language: "English",
    address: "No.56, 7 Fl, Kyaukmyuang St, Tamwe Tsp, Ygn.",
    phone: "95175380",
  },
  {
    no: "135",
    name: "U Sein Phay",
    licenseNo: "G-0460",
    licenseDate: "",
    language: "English",
    address: "No.17, Shwezayti St, Pathein Tsp, Ayeyarwady Division.",
    phone: "",
  },
  {
    no: "136",
    name: "U Aung Thein",
    licenseNo: "G-0465",
    licenseDate: "",
    language: "English",
    address: "No.291, Bosonpat St, Pabedan Tsp, Ygn.",
    phone: "",
  },
  {
    no: "137",
    name: "Daw Nu Nu Yin",
    licenseNo: "G-0469",
    licenseDate: "",
    language: "English/French",
    address: "No.83/85, 54 St, Botathaung Tsp, Ygn.",
    phone: "01203129/095006844",
  },
  {
    no: "138",
    name: "U Yan Naing",
    licenseNo: "G-0475",
    licenseDate: "",
    language: "English",
    address: "No.48, Hlaing Lane(14), E/Yankin Tsp, Ygn.",
    phone: "",
  },
  {
    no: "139",
    name: "Daw Sandar Win",
    licenseNo: "G-0479",
    licenseDate: "",
    language: "English/French",
    address: "Bldg.295/Rm.3, E/Yankin Tsp, Ygn.",
    phone: "243185",
  },
  {
    no: "140",
    name: "Daw Khin Than Win",
    licenseNo: "G-0487",
    licenseDate: "",
    language: "English/Japanese",
    address: "No.40, Rm. 7, 48 St, 10 Qr, Botathaung Tsp, Ygn.",
    phone: "",
  },
  {
    no: "141",
    name: "U Thaung Tin",
    licenseNo: "G-0488",
    licenseDate: "",
    language: "English/French",
    address: "No.700, Zawtika St, 16/4 Qr, Thingangyun Tsp, Ygn.",
    phone: "930194306",
  },
  {
    no: "142",
    name: "U Aung Kyaw Oo",
    licenseNo: "G-0491",
    licenseDate: "",
    language: "English",
    address: "No.199/ Bouang Kyaw St, Kyauktada Tsp, Ygn.",
    phone: "",
  },
  {
    no: "143",
    name: "U Nyi Nyi Lwin",
    licenseNo: "G-0494",
    licenseDate: "",
    language: "English",
    address: "No.27, Garden St, Bahan Tsp, Ygn.",
    phone: "",
  },
  {
    no: "144",
    name: "Daw Myint Myint Oo",
    licenseNo: "G-0495",
    licenseDate: "",
    language: "English/German",
    address: "No.5/2, kaulkytin St, Thingangyun Tsp, Ygn.",
    phone: "",
  },
  {
    no: "145",
    name: "Daw Moe Kyi Win",
    licenseNo: "G-0500",
    licenseDate: "",
    language: "English/Japanese",
    address: "No.15, Rm. 3 , 3 St, Myoma Qr, Bahan Tsp, Ygn.",
    phone: "245813",
  },
  {
    no: "146",
    name: "Daw Zon Pwint",
    licenseNo: "G-0505",
    licenseDate: "",
    language: "English",
    address: "No.102/A, Damazatyit St, 3 Fl, Bahan Tsp, Ygn.",
    phone: "95121659",
  },
  {
    no: "147",
    name: "U Nu Nu Aye",
    licenseNo: "G-0512",
    licenseDate: "",
    language: "English/Japanese",
    address: "No.54/56 St & Thukha St, 7 Qr, Hlaing Tsp, Ygn.",
    phone: "",
  },
  {
    no: "148",
    name: "U Mya Min Dim",
    licenseNo: "G-0514",
    licenseDate: "",
    language: "English",
    address: "No.130, U Cho St, 8 Qr, Hlaing Tsp, Ygn.",
    phone: "925402652",
  },
  {
    no: "149",
    name: "Daw Yin Min Lwin",
    licenseNo: "G-0526",
    licenseDate: "",
    language: "English/French",
    address: "No.29/B, New University Yeiktha ,Sayarsan Qr,BahanTsp, Ygn.",
    phone: "",
  },
  {
    no: "150",
    name: "U Myint Khaing Oo",
    licenseNo: "G-0528",
    licenseDate: "",
    language: "English",
    address: "No.3, Pyi St, 8 miles, Mayangone Tsp,Ygn.",
    phone: "01665001/095191580",
  },
   {
    no: "151",
    name: "Daw San San Win",
    licenseNo: "G-0531",
    licenseDate: "",
    language: "French",
    address: "No.54, Natchaung, Tamwe Tsp, Ygn.",
    phone: "98636507",
  },
  {
    no: "152",
    name: "Daw Myo Nwe Nwe Tun",
    licenseNo: "G-0535",
    licenseDate: "",
    language: "English",
    address: "Bldg.13, Rm.01, Malikha Housing, Yadanar St, Thingangyun Tsp, Ygn.",
    phone: "",
  },
  {
    no: "153",
    name: "U Nyi Nyi Kyaw",
    licenseNo: "G-0539",
    licenseDate: "",
    language: "English",
    address: "No.38, Thida St, Kyaukmyuang, Tamwe Tsp, Ygn.",
    phone: "",
  },
  {
    no: "154",
    name: "Daw Thandar Cho",
    licenseNo: "G-0552",
    licenseDate: "",
    language: "English/French",
    address: "No.404/31, Bonyarna St, N/Dagon Tsp, Ygn",
    phone: "95155383",
  },
  {
    no: "155",
    name: "Daw Tin Tin May",
    licenseNo: "G-0553",
    licenseDate: "",
    language: "French",
    address: "No.479, Aungtha-pyay, E/6, St 7 Qr, G-Thakyta Tsp, Ygn.",
    phone: "945006784",
  },
  {
    no: "156",
    name: "U Than Hlaing",
    licenseNo: "G-0556",
    licenseDate: "",
    language: "English/Japanese",
    address: "No.19, Pantar St, Yawmimgyi Qr, Dagon Tsp, Ygn.",
    phone: "95143612",
  },
  {
    no: "157",
    name: "Daw Aye Aye Khaing",
    licenseNo: "G-0565",
    licenseDate: "",
    language: "English",
    address: "No.16, Pawtawmut St, Thamine, Mayangone Tsp, Ygn.",
    phone: "",
  },
  {
    no: "158",
    name: "Daw Mi Mi Htike",
    licenseNo: "G-0567",
    licenseDate: "",
    language: "English/French/Japanese",
    address: "Bldg.87, Rm.2, 2 Fl, Sanyiekyne, Kamaryut Tsp, Ygn.",
    phone: "",
  },
  {
    no: "159",
    name: "Daw Cho Thi Lwin",
    licenseNo: "G-0568",
    licenseDate: "",
    language: "English/Italian",
    address: "Bldg/kha/5, Bandagoner (3) St, Kandawkalay, Mingalar Taung Nyunt Tsp, Ygn.",
    phone: "",
  },
  {
    no: "160",
    name: "U Kyaw Oo",
    licenseNo: "G-0571",
    licenseDate: "",
    language: "English",
    address: "No.326, Tabin Shwhetee St, 11 Qr, E/Dagon Myothit, Ygn.",
    phone: "",
  },
  {
    no: "161",
    name: "Daw Baby Aye",
    licenseNo: "G-0575",
    licenseDate: "",
    language: "English",
    address: "No.119/9, Nadawi St, YeatarShae Qr, Bahan Tsp, Ygn.",
    phone: "",
  },
  {
    no: "162",
    name: "Daw Myint Myint Aye",
    licenseNo: "G-0588",
    licenseDate: "",
    language: "English/French",
    address: "No.33, 1 Flr, 28-St, Bapedan Tsp, Ygn.",
    phone: "",
  },
  {
    no: "163",
    name: "U Kyaw Khaing",
    licenseNo: "G-0589",
    licenseDate: "",
    language: "Japanese",
    address: "No.131, Fairy Tauang 1 St, 40 Qr, N/Dagon Tsp, Ygn.",
    phone: "9799940507",
  },
  {
    no: "164",
    name: "Daw Aye Aye Win",
    licenseNo: "G-0591",
    licenseDate: "",
    language: "English",
    address: "No.9, Damaseikdar St, Kyaukmyuang, Tamwe Tsp, Ygn.",
    phone: "",
  },
  {
    no: "165",
    name: "Daw Maw Maw Myint",
    licenseNo: "G-0592",
    licenseDate: "",
    language: "English",
    address: "No.5/Ka, Aung Zaya (8) St, New Yagon Qr, Thingangyun Tsp, Ygn.",
    phone: "254431",
  },
  {
    no: "166",
    name: "Daw Aye Aye",
    licenseNo: "G-0601",
    licenseDate: "",
    language: "English",
    address: "No.82, 2nd Fl, 49 St, Puzundaung Tsp, Ygn.",
    phone: "",
  },
  {
    no: "167",
    name: "U Kyaw Thu",
    licenseNo: "G-0602",
    licenseDate: "",
    language: "English",
    address: "No.28, 2nd Fl, Kyaukmyung, Tamwe Tsp, Ygn.",
    phone: "",
  },
  {
    no: "168",
    name: "U Ye Tun Win",
    licenseNo: "G-0604",
    licenseDate: "",
    language: "English/French",
    address: "No.38/2, Zinyaw St, 14/2 Qr, S/Okkalapa Tsp, Ygn.",
    phone: "95134379",
  },
  {
    no: "169",
    name: "Daw Sein Sein Lin",
    licenseNo: "G-0607",
    licenseDate: "",
    language: "English/French/Spanish",
    address: "No.25/29, 1st Fl, Shwe Dagon Pagoda Rd, Latha Tsp, Ygn.",
    phone: "",
  },
  {
    no: "170",
    name: "Daw Kha Mar Zaya",
    licenseNo: "G-0609",
    licenseDate: "",
    language: "English",
    address: "No.2/24, U Waisara Housing, Dagon Tsp, Yangon.",
    phone: "",
  },
  {
    no: "171",
    name: "Daw May Khaing Tun",
    licenseNo: "G-0620",
    licenseDate: "",
    language: "English",
    address: "Bldg(25), Rm(401), Yazadi Housing, Botathaung Tsp, Ygn.",
    phone: "",
  },
  {
    no: "172",
    name: "Daw Ei Win Than",
    licenseNo: "G-0621",
    licenseDate: "",
    language: "English/French",
    address: "no292/5, Yan Aung lane(2), Yankin Tsp, Ygn.",
    phone: "",
  },
  {
    no: "173",
    name: "Daw Kyi Kyi San",
    licenseNo: "G-0632",
    licenseDate: "",
    language: "English",
    address: "No(B/40/15), Nawady Housing, Hlaingtharyar Tsp, Ygn.",
    phone: "",
  },
  {
    no: "174",
    name: "Daw In In Thwe",
    licenseNo: "G-0635",
    licenseDate: "",
    language: "English",
    address: "No(80/B), Khwarnyo St, Pyusawthe Qr, Bagan Myothit, Mdy.",
    phone: "200650",
  },
  {
    no: "175",
    name: "U Kyaw Soe Lat",
    licenseNo: "G-0637",
    licenseDate: "",
    language: "English",
    address: "No(503), Shwewaymyar Bldg(2), 9 Qr, Insein Rd, Hlaing Tsp, Ygn.",
    phone: "",
  },
  {
    no: "176",
    name: "U Phaye Thet Oo",
    licenseNo: "G-0640",
    licenseDate: "",
    language: "English",
    address: "Bld; 11, Rm;404, 10-St, 94-Qr, Dagon Seikkan Myothit Tsp, Ygn.",
    phone: "9420102953",
  },
  {
    no: "177",
    name: "U Tin Myo Aung",
    licenseNo: "G-0649",
    licenseDate: "",
    language: "Japanese",
    address: "No(308), Nilar 5 St, 8 Qr, N/Okkalapa Tsp, Ygn.",
    phone: "95125375",
  },
  {
    no: "178",
    name: "U Htin Gyi",
    licenseNo: "G-0652",
    licenseDate: "",
    language: "English/Italian/Spanish",
    address: "No(68), Shwedagon Pagoda Rd, Dagon Tsp, Ygn.",
    phone: "",
  },
  {
    no: "179",
    name: "U Ye Win Naing",
    licenseNo: "G-0656",
    licenseDate: "",
    language: "English/Spanish",
    address: "Bldg(2/22), Kamuyut Tsp, Ygn.",
    phone: "92042966",
  },
  {
    no: "180",
    name: "U Tun Min",
    licenseNo: "G-0660",
    licenseDate: "",
    language: "English/German",
    address: "No(1268), Naungcho St, 40 Qr, N/Dagon Tsp, Ygn.",
    phone: "549188",
  },
  {
    no: "181",
    name: "Daw Nan Phoung Sihe",
    licenseNo: "G-0662",
    licenseDate: "",
    language: "English/Thai",
    address: "No(32/3 kha), Aungtawmu St, S/Mayingone Qr, Sanchaung Tsp, Ygn.",
    phone: "",
  },
  {
    no: "182",
    name: "Daw Swe Swe Thant",
    licenseNo: "G-0665",
    licenseDate: "",
    language: "English/Russian",
    address: "No(867), Kyawhtu 20 St, 9 Qr, S/Okkalapa Tsp, Ygn.",
    phone: "9420034163",
  },
  {
    no: "183",
    name: "U Twin Myat Kyaw",
    licenseNo: "G-0667",
    licenseDate: "",
    language: "English",
    address: "No(132), Nanthargone Yeikthar St, Insein Tsp, Ygn.",
    phone: "",
  },
  {
    no: "184",
    name: "Daw Nwet Yin Win",
    licenseNo: "G-0673",
    licenseDate: "",
    language: "English",
    address: "No(67), 39 St, Bet. 84, 85, Maharaugnmyay Tsp, Ygn.",
    phone: "",
  },
  {
    no: "185",
    name: "Tha Toe Thuzar Aung",
    licenseNo: "G-0674",
    licenseDate: "",
    language: "English/French",
    address: "No(46), Maharazaya St, Mingalar Taung Nyunt Tsp, Ygn.",
    phone: "",
  },
  {
    no: "186",
    name: "Daw In Gyin Zaw",
    licenseNo: "G-0691",
    licenseDate: "",
    language: "English",
    address: "No(70), 2-Flr, Htanar St, Htanar Qr, Ahlone Tsp, Ygn.",
    phone: "643748",
  },
  {
    no: "187",
    name: "U Myat Thu",
    licenseNo: "G-0694",
    licenseDate: "",
    language: "English",
    address: "No(5/A), Thitsar St, KyanKhinSu Qr, Mingalardon Tsp, Ygn.",
    phone: "94391248",
  },
  {
    no: "188",
    name: "U Thet Aung Tun",
    licenseNo: "G-0706",
    licenseDate: "",
    language: "English/French",
    address: "No(202/19), Yankin Tsp, Ygn.",
    phone: "",
  },
  {
    no: "189",
    name: "Orr D Yi Jap Sin",
    licenseNo: "G-0714",
    licenseDate: "",
    language: "English",
    address: "No(Ma/12), Jubal St, Taungthugone Qr, Insein Tsp, Ygn.",
    phone: "",
  },
  {
    no: "190",
    name: "U Kyaw Thu Ya",
    licenseNo: "G-0722",
    licenseDate: "",
    language: "English/Italian",
    address: "No(134/6/ka), Myanmar Gonyae St, Mingalartaungnyut Tsp, Ygn.",
    phone: "92044317",
  },
  {
    no: "191",
    name: "Daw Thein Gee Lwin",
    licenseNo: "G-0723",
    licenseDate: "",
    language: "English+Spanish",
    address: "No(204), Ziwasoe St, 14/2 Myintnar, S/Okkalapa Tsp, Ygn.",
    phone: "95115521",
  },
  {
    no: "192",
    name: "Daw Mhae Mhae",
    licenseNo: "G-0730",
    licenseDate: "",
    language: "English",
    address: "No(B/6), Thanthumar St, (24) Qr, Thingangyun Tsp, Ygn.",
    phone: "",
  },
  {
    no: "193",
    name: "Daw Nu Nwe Soe",
    licenseNo: "G-0735",
    licenseDate: "",
    language: "English/Thai",
    address: "Bldg(2), Rm(205), Aungmyaytharzan Housing, Kamayut Tsp, Ygn.",
    phone: "",
  },
  {
    no: "194",
    name: "Daw Ohmar Tun",
    licenseNo: "G-0742",
    licenseDate: "",
    language: "English",
    address: "Bldg(16), Rm (5), Wailuwun Housing, Sanchaung Tsp, Ygn.",
    phone: "",
  },
  {
    no: "195",
    name: "U Mg Mg Kyaw",
    licenseNo: "G-0745",
    licenseDate: "",
    language: "English",
    address: "No(10), Thingaha St, 3 Fl, Tamwe Tsp, Ygn.",
    phone: "",
  },
  {
    no: "196",
    name: "Daw Thwe Thwe Aye",
    licenseNo: "G-0747",
    licenseDate: "",
    language: "English/German/Japanese",
    address: "No(24), E/ Circular Rd, Kalaw, Shan State.",
    phone: "",
  },
  {
    no: "197",
    name: "U Thet Oo",
    licenseNo: "G-0755",
    licenseDate: "",
    language: "English",
    address: "No-69/7, Kamar St, 24-Qr, Thuwunna, Thingangyun Tsp, Ygn.",
    phone: "97303352",
  },
  {
    no: "198",
    name: "Daw Yin Yin Than",
    licenseNo: "G-0756",
    licenseDate: "",
    language: "English",
    address: "Bldg(6), Rm10, Mingalartaungnyut Tsp, Ygn.",
    phone: "01293119/09731350797",
  },
  {
    no: "199",
    name: "Nor Za Yi Nar",
    licenseNo: "G-0758",
    licenseDate: "",
    language: "English",
    address: "No(387), W/Kyogoone, Baho St, Insein Tsp, Ygn.",
    phone: "",
  },
  {
    no: "200",
    name: "Ga Lan Thar Sa Tan",
    licenseNo: "G-0761",
    licenseDate: "",
    language: "English/French",
    address: "No(74), 50 St, Puzuntaung Tsp, Ygn.",
    phone: "388815",
  },
  
];

export const metadata = {
  title: "National Tour Guides",
  description: "Myanmar Tourism Office has national tour guides in Myanmar"
};

export default function NationalTourGuide() {
  return (
    <div className={styles.pageContainer}>
      <BannerSection imageUrl="/assets/images/cover-images/56.jpg" altText="national tour guide cover photo" />
      <Breadcrumb
        items={[
          { label: "Trang chủ", href: "/vn", icon: faHome },
          { label: "National Tour Guides", active: true }
        ]}
      />
      <div className={styles.container}>
        <h1 className={styles.pageTitle}>National Tour Guides</h1>
        {/* <p className={styles.paragraph}>နိုင်ငံတော်ခရီးသွားလမ်းပြများ၏ အချက်အလက်များကို ရှာဖွေနိုင်ပါသည်။</p> */}
        <div className={styles.tableResponsive}>
          <table className={styles.guideTable}>
            <thead>
              <tr>
                <th>No.</th>
                <th>Name</th>
                <th>License No</th>
                <th>Language</th>
                <th>Address</th>
                <th>Contact Phone</th>
              </tr>
            </thead>
            <tbody>
              {tourGuides.map((guide, idx) => (
                <tr key={idx}>
                  <td>{guide.no}</td>
                  <td>{guide.name}</td>
                  <td>{guide.licenseNo}</td>
                  <td>{guide.language}</td>
                  <td>{guide.address}</td>
                  <td>{guide.phone}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}